version: '3'
services:
  
  web:
    build: .
    ports:
      - "8080:8080"
  db:
    container_name: mysql-dev
    image: mysql:5.7
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
    volumes:
      - db-data:/foo

volumes:
  db-data: